set wshshell=createobject ("wscript.shell" )
d=wshshell.run ("AutoHotkey ""C:\cygwin64\home\Pandari\ahk\leftParen.ahk""",3)
d=wshshell.run ("AutoHotkey ""C:\cygwin64\home\Pandari\ahk\rightParen.ahk""",3)
d=wshshell.run ("AutoHotkey ""C:\cygwin64\home\Pandari\ahk\terminalize.ahk""",3)
d=wshshell.run ("AutoHotkey ""C:\cygwin64\home\Pandari\ahk\switcher.ahk""",3)